# ===================================================================
# Spring Boot configuration for the "dev" profile.
#
# This configuration overrides the application.yml file.
#
# ===================================================================
logging:
  #日志
  level:
    ROOT: debug
    com.ctsi.sampleapp: debug

spring:
  profiles:
    active: dev
    include: swagger
  jackson:
    serialization.indent_output: true
    #时区
    time-zone: GMT+8
  jpa:
    hibername:
      ddl-auto: none

  liquibase:
    #数据库初始化
    enabled: true
    change-log: classpath:/db/changelog/master.xml
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://10.211.55.4:3306/develop?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    type: com.zaxxer.hikari.HikariDataSource
    username: rsyslog
    password: 12345678
    hikari:
      #最大连接池数
      maximumPoolSize: 20
      data-source-properties:
      cachePrepStmts: true
      prepStmtCacheSize: 250
      prepStmtCacheSqlLimit: 2048
      useServerPrepStmts: true
  redis:
    database: 0
    host: 10.211.55.9
    port: 6379
    password:
    timeout: 2000ms
    jedis:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1ms
  #国际化
  messages:
    basename: i18n/messages
    encoding: UTF-8
server:
  #端口号
  port: 9000

ctsi:
  # CORS is only enabled by default with the "dev" profile, so BrowserSync can access the API
  cors:
    allowed-origins: "*"
    allowed-methods: "*"
    allowed-headers: "*"
    exposed-headers: "Authorization,Link,X-Total-Count"
    allow-credentials: true
    max-age: 1800
  #允许跨域，多个以逗号分隔
  corspaths: "/api/**"
  #新增用户默认密码
  login-password: ctsi1234
  log:
    #是否启用操作日志
    operation-log:
      enable: false
    #是否启用登录日志
    login-log:
      enable: false
  security:
    authentication:
      jwt:
        #token key密钥
        secret: my-secret-token-to-change-in-production
        #token失效时间，秒
        token-validity-in-seconds: 86400
        #rememberme token失效时间
        token-validity-in-seconds-for-remember-me: 2592000
  captcha:
    #验证码KEY策略
    keyProvider: simpleCaptchaKeyProvider
    #验证码组件缓存实现，提供两种实现，redis和基于guava的缓存，redis支持集群部署，guava只支持单机使用。可选值：guavaCaptchaCache，redisCaptchaCache
    cache: guavaCaptchaCache
  access:
    #组织名
    groupId: ${project.groupId}
    #项目名
    projectName: ${project.artifactId}
    #项目版本
    projectVersion: ${project.version}
    #组件使用用户（比翼平台账号用户名）
    userName: yuhaiyang
    #是否启用组件统计，关闭则无法上报组件调用量，影响积分
    #enable: true
    #统计信息发送地址
    url: https://s.ctbiyi.com/api
    #日志文件
    filePath: /Users/tongliwei
    #发送策略，毫秒
    scheduledRate: 180000
  datasource:
    db:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://10.211.55.4:3306/service?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
      type: com.zaxxer.hikari.HikariDataSource
      username: rsyslog
      password: 12345678
      hikari:
        #最大连接池数
        maximumPoolSize: 5
        data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
#mybatis配置
mybatis:
  configLocation: classpath:/mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径

pagehelper:
  #分页设置
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  pageSizeZero: true

management:
  health:
    redis:
      #关闭REDIS健康检查
      enabled: false